# Generated by Django 4.0.6 on 2022-08-24 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fnews',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='No Title Available', max_length=800)),
                ('pr_id', models.IntegerField(default=-1)),
                ('pr_per_cent', models.FloatField()),
                ('url', models.TextField()),
                ('date', models.DateField()),
                ('src', models.CharField(default='Internet', max_length=40)),
                ('flags', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Prel',
            fields=[
                ('pr_id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=800)),
                ('url', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20)),
                ('passwrd', models.CharField(max_length=20)),
            ],
        ),
    ]
