# Generated by Django 4.1 on 2022-08-26 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fnews',
            name='sus_fac',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
